### ISSUE TITLE
Not working with IE11?

### ISSUE THREAD

**Issue by cheahkhing** [jasonslyvia/react-lazyload#51] opened 2016-09-30 01:31 UTC
Hi,
i tried the demo page with IE11, nothing get loaded. Is this a known issue?

**Comment by NeXTs** [comment] 2016-10-07 22:00
same here
got `Object doesn't support property or method 'fill'`
`File: bundle.min.js, Line: 17, Column: 26022`

**Comment by jasonslyvia** [comment] 2016-10-10 00:45
I guess it's caused by this line https://github.com/jasonslyvia/react-lazyload/blob/7b282db4f811871c43d31d2e1e81c7e387210abd/examples/pages/normal.js#L13

But it's just the demo, source code won't be affected.

**Comment by NeXTs** [comment] 2016-10-10 12:38
But people may be afraid that main library was not designed to work at IE and it may be main reason to avoid this library.
So that such small nuances matters in making decision regarding which library use

**Comment by jasonslyvia** [comment] 2016-10-10 13:15
@NeXTs Agreed, it will be replaced with more compatible syntax, thanks!

**Comment by jasonslyvia** [comment] 2016-10-11 12:41
It should be fixed in 7e2ceb9

**Closed by jasonslyvia** 2016-10-11 12:41 UTC
